### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by corygibbons**

### CODE REVIEW

**Comment by njuro** [comment]
Hey, can you wait a few minutes merging this PR/updating versions? :D I want to open very minor PR myself, so it could be included in 1.0.0 as well

**Comment by corygibbons** [comment]
@njuro For sure 👌

**Comment by njuro** [comment]
@corygibbons thanks, it was just 1 line in the end -> #16

**Comment by njuro** [comment]
@corygibbons may I ask, why did you decide to remove `size` property? I am now trying to style it using css with maxWidth and maxHeight, but it doesn't quite work.

**Comment by corygibbons** [comment]
@njuro The sizing already wasn't precise visually because there was built in horizontal spacing on both sides of the icon. So setting `size={48}` was really giving you an icon that was around `42px` wide, and you'd have to factor in the that space to get precise alignment between `FileIcon`'s and other elements.

`size` wasn't necessary in the use cases I was testing but I'll look into it further and potentially bring it back in some capacity, might be better naming it `maxWidth` as that's really what it's doing.

In the meantime including something like `svg { max-width: 100%; }` in your app should hopefully solve the height problem for you, allowing the icon to scale within a box always staying within it's `width` and `height`.

> but I think it should be highlighted in the readme (that icon will be always 100% size of parent container)

I had it in the release notes for breaking changes but makes sense to include in the readme as well, I'll ad it 👍

**Pull request merged**
